[development]
databases = { diesel = { url="postgres://wiki_user:test@localhost:5432/postgres?options=-c search_path%3Dmain" } }

[test]
databases = { diesel = { url="postgres://wiki_user:test@localhost:5432/postgres?options=-c search_path%3Dtest" } }
